/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RecvAsyncOptions {
  signal?: AbortSignal
}
export interface JsFrame {
  channel: number
  payload: Buffer
}
export interface ListenerOptions {
  channels?: Array<number>
  schemaDir?: string
}
export declare function control(): number
export declare function command(): number
export declare function data(): number
export declare function telemetry(): number
export declare function error(): number
export declare const CONTROL: number
export declare const COMMAND: number
export declare const DATA: number
export declare const TELEMETRY: number
export declare const ERROR: number
export declare class AsyncPeer {
  static connect(path: string, channels: Array<number>): Promise<AsyncPeer>
  send(channel: number, data: Buffer): Promise<void>
  recvAsync(options?: RecvAsyncOptions | undefined | null): Promise<JsFrame>
  recvOnAsync(channel: number, options?: RecvAsyncOptions | undefined | null): Promise<JsFrame>
  openChannel(channel: number): Promise<AsyncChannelReceiver>
  ping(): Promise<number>
  shutdown(): Promise<void>
  close(): void
}
export declare class AsyncChannelReceiver implements AsyncIterable<JsFrame> {
  recvAsync(options?: RecvAsyncOptions | undefined | null): Promise<JsFrame>
  [Symbol.asyncIterator](): AsyncIterator<JsFrame>
}
export declare class AsyncListener {
  static bind(path: string, options?: ListenerOptions | undefined | null): AsyncListener
  accept(): Promise<AsyncPeer>
  close(): Promise<void>
}
export declare class Listener {
  static bind(path: string, options?: ListenerOptions | undefined | null): Listener
  accept(): Peer
  close(): void
}
export declare class Peer {
  static connect(path: string, channels: Array<number>): Peer
  send(channel: number, data: Buffer): void
  recv(): JsFrame
  recvOn(channel: number): JsFrame
  ping(): number
  shutdown(): void
  close(): void
}
export declare class SchemaRegistry {
  static fromDirectory(path: string): SchemaRegistry
  validate(channel: number, data: Buffer): void
  close(): void
}
