/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsFrame {
	channel: number;
	payload: Buffer;
}
export interface ListenerOptions {
	channels?: Array<number>;
	schemaDir?: string;
}
export declare function control(): number;
export declare function command(): number;
export declare function data(): number;
export declare function telemetry(): number;
export declare function error(): number;
export declare class Listener {
	static bind(
		path: string,
		options?: ListenerOptions | undefined | null,
	): Listener;
	accept(): Peer;
	close(): void;
}
export declare class Peer {
	static connect(path: string, channels: Array<number>): Peer;
	send(channel: number, data: Buffer): void;
	recv(): JsFrame;
	recvOn(channel: number): JsFrame;
	ping(): number;
	shutdown(): void;
	close(): void;
}
export declare class SchemaRegistry {
	static fromDirectory(path: string): SchemaRegistry;
	validate(channel: number, data: Buffer): void;
	close(): void;
}
